# Generated by Django 4.2.6 on 2023-11-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=255)),
                ('provincia', models.CharField(max_length=255)),
                ('cpostal', models.CharField(max_length=255)),
            ],
        ),
    ]
